services:
  terraria:
    build: .
    container_name: terraria-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "7777:7777"
    volumes:
      # Map the worlds folder so you don't lose progress on container rebuilds
      - ./worlds:/terraria/Worlds
      # Map the config so you can tweak settings without rebuilding
      - ./serverconfig.txt:/terraria/serverconfig.txt
    environment:
      - BOX64_LOG=1 # Enable logs for debugging
      - BOX64_PAGE_SIZE=16384
      - BOX64_DYNAREC_STRONGMEM=1
      - BOX64_DYNAREC_BIGBLOCK=0
      - BOX64_DYNAREC_FASTROUND=1
    deploy:
      resources:
        limits:
          memory: 4G
